 NAME = OM MENGE BRANCH = CO 

In [5]:
import numpy as np


# 1. Create array
arr = np.array([1, 2, 3, 4, 5])
print("1. arr:", arr)


# 2. Array of zeros
zeros = np.zeros((2, 3))
print("\n2. zeros:\n", zeros)


# 3. Array of ones
ones = np.ones((3, 2))
print("\n3. ones:\n", ones)

# 4. Identity matrix
identity = np.eye(3)
print("\n4. identity:\n", identity)

# 5. Create range of numbers
range_arr = np.arange(0, 10, 2)
print("\n5. range_arr:", range_arr)


# 6. Reshape array
reshaped = np.arange(12).reshape((3, 4))
print("\n6. reshaped:\n", reshaped)


# 7. Random numbers
rand_arr = np.random.rand(2, 3)
print("\n7. rand_arr:\n", rand_arr)


# 8. Transpose
transposed = reshaped.T
print("\n8. transposed:\n", transposed)

# 9. Flatten array
flattened = reshaped.flatten()
print("\n9. flattened:", flattened)


# 10. Stack arrays vertically
a = np.array([1, 2])
b = np.array([3, 4])
v_stack = np.vstack((a, b))
print("\n10. v_stack:\n", v_stack)


# 11. Stack arrays horizontally
h_stack = np.hstack((a, b))
print("\n11. h_stack:", h_stack)


# 12. Element-wise addition
sum_arr = a + b
print("\n12. sum_arr:", sum_arr)


# 13. Element-wise multiplication
product_arr = a * b
print("\n13. product_arr:", product_arr)


# 14. Array slicing
slice_arr = arr[1:4]
print("\n14. slice_arr:", slice_arr)


# 15. Max, Min, Mean
max_val = arr.max()
min_val = arr.min()
mean_val = arr.mean()
print("\n15. max:", max_val)   
print("    min:", min_val)     
print("    mean:", mean_val)   


1. arr: [1 2 3 4 5]

2. zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

3. ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

4. identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

5. range_arr: [0 2 4 6 8]

6. reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

7. rand_arr:
 [[0.18643409 0.85921673 0.15641528]
 [0.5933897  0.92944139 0.28341965]]

8. transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

9. flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

10. v_stack:
 [[1 2]
 [3 4]]

11. h_stack: [1 2 3 4]

12. sum_arr: [4 6]

13. product_arr: [3 8]

14. slice_arr: [2 3 4]

15. max: 5
    min: 1
    mean: 3.0
